CREATE DATABASE ArtisanCafe;
GO

USE ArtisanCafe;
GO

CREATE TABLE dbo.[User] (
    UserId INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
